check if pyproject version and tag match

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -32,9 +32,13 @@ jobs:
                   GITHUB_REF_NAME: ${{ github.ref_name }}
               run: |
                   VERSION=$(echo "$GITHUB_REF_NAME" | sed 's/^v//')
-                  echo "Updating version to $VERSION"
-                  sed -i "s|^version = .*|version = \"$VERSION\"|" pyproject.toml
-                  cat pyproject.toml
+                  CURR =$(cat pyproject.toml | grep ^version | sed 's/version = "\(.*\)"/\1/')
+                  if [ "$VERSION" != "$CURR" ]; then
+                      echo "Error: VERSION ($VERSION) and CURR ($CURR) do not match."
+                      exit 1
+                  else
+                      echo "VERSION ($VERSION) matches CURR ($CURR). Proceeding."
+                  fi
 
             - name: Build package
               run: python -m build
@@ -44,17 +48,6 @@ jobs:
               with:
                   user: __token__
                   password: ${{ secrets.PYPI_API_TOKEN }}
-
-            - name: Commit and push changes
-              env:
-                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-              run: |
-                  git config user.name 'github-actions[bot]'
-                  git config user.email 'github-actions[bot]@users.noreply.github.com'
-                  git add pyproject.toml
-                  git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
-                  git commit -m "Update version to ${{ github.ref_name }}"
-                  git push origin master
 
     build-docs:
         needs: deploy
